sudo: required

services:
  - docker

## Test if the container can build
before_install:
  - docker pull seankross/bologna

## A small test
script:
  - Rscript ari_test.R
  - Rscript -e 'testthat::expect_true(file.size("output.mp4") > 50000);'
  - rm -f output.mp4
